name: "Docker build"
description: "Build docker image of project"

inputs:
  node-version:
    description: The node version to build the image on
    required: true
  image-name:
    description: What to tag the built image as
    required: true
    default: traffic-analytics
  build-production:
    description: Whether to build the full image when no targets are specified
    required: false
    default: 'true'
  build-multiarchitecture:
    description: Wether to build a multi-architecture image or not
    required: true
    default: 'false'

outputs:
  production-image-name:
    description: The tag used for the built production image
    value: ${{ inputs.image-name }}:latest
  base-image-name:
    description: The tag used for the built base image
    value: ${{ inputs.image-name }}:base
  production-image-built:
    description: Whether the production image was built
    value: ${{ inputs.build-production }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
<<<<<<< HEAD
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      id: build-docker-image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ inputs.image-name }}
        build-args: |
          NODE_VERSION=${{ inputs.node-version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
=======

    - name: Set up Docker
      uses: docker/setup-docker-action@v4
      if: inputs.build-multiarchitecture == 'true'
      with:
        daemon-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          }

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      if: inputs.build-multiarchitecture == 'true'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: inputs.build-multiarchitecture == 'true'

    - name: Build base docker image
      id: build-base-docker-image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: base
        tags: ${{ inputs.image-name }}:base
        build-args: |
          NODE_VERSION=${{ inputs.node-version }}
        platforms: ${{ inputs.build-multiarchitecture == 'true' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
        load: ${{ inputs.build-multiarchitecture == 'true' && true || false }}

    - name: Build production docker image
      id: build-production-docker-image
      if: ${{ inputs.build-production == 'true' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ inputs.image-name }}:latest
        build-args: |
          NODE_VERSION=${{ inputs.node-version }}
        platforms: ${{ inputs.build-multiarchitecture == 'true' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
        load: ${{ inputs.build-multiarchitecture == 'true' && true || false }}
>>>>>>> 08ca955649c4e4320b56232fc8bbc71bbb9b8560
